services:
  loki:
    image: grafana/loki:latest
    container_name: loki
    ports:
      - "3100:3100"
    networks:
      - backend-network

  promtail:
    image: grafana/promtail:latest
    container_name: promtail
    volumes:
      - ./promtail-config.yml:/etc/promtail/promtail-config.yml
      - logs_volume:/app/logs
    networks:
      - backend-network
    command: -config.file=/etc/promtail/promtail-config.yml

networks:
  backend-network:
    external: true

volumes:
  logs_volume:
    external: true
